# Generated by Django 6.0 on 2026-01-24 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_content_file_image_text_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='file',
            new_name='url',
        ),
    ]
