# Generated by Django 6.0 on 2026-01-27 03:19

import apps.courses.files
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_file_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='order',
            field=apps.courses.files.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=apps.courses.files.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
